### ISSUE TITLE
Jira collector not showing data related to story,epics.

### ISSUE THREAD

**Issue by continuum-vikrant-tyagi** [Hygieia/hygieia-feature-jira-collector#14]
@amitmawkin we are implementing Hygieia, and while configure jira-collector face some issue with data populating. I have raise same in one of similar issue comment.

If you see we are not able to get the data of Epics and In Progress at all..

Kindly you or team can help to get resolve this.
thanks

https://github.com/Hygieia/hygieia-feature-jira-collector/issues/5#issuecomment-519777039

![image](https://user-images.githubusercontent.com/33453392/64425306-fab95f80-d0c8-11e9-9217-152feb44ab73.png)

**Comment by continuum-vikrant-tyagi** [comment]
Hi @Sbrenthughes  I've delete/drop the mentioned 3 collections and give a restart but no luck..

still there is no data push in feature collection but at the same scope and team collections has data.

**Comment by Sbrenthughes** [comment]
Can you message me on gitter?

**Comment by evan853** [comment]
> Hi @Sbrenthughes I've delete/drop the mentioned 3 collections and give a restart but no luck..
> 
> still there is no data push in feature collection but at the same time scope and team collections has data.

Hi @continuum-vikrant-tyagi , have this problem been solved? We encountered the same problem. Thanks.

**Comment by continuum-vikrant-tyagi** [comment]
Hi @evan853  Not yet !! looking forwards this.

**Comment by Navya-V** [comment]
hi **@continuum-vikrant-tyagi**  is ur issue resoved .i am currently facing the same issue.if resoved please post the solution

**Comment by continuum-vikrant-tyagi** [comment]
@Navya-V  not yet, will cross check once again with team.

**Comment by Navya-V** [comment]
Thanks @continuum-vikrant-tyagi  for your reply . please reply after you check. Thanks in Advance

**Comment by Navya-V** [comment]
The issues that are tagged as **story** are displayed and other issues that are **Tasks,Tests ,Bugs** are not collected by jira-collector and are not displayed in the Jira dashboard .though i have mentioned them as feature.jiraIssueTypeNames=Story, Bug, Task, Sub-task ,Test, Epic in properties file. Can anybody suggest what can be done for this.

Any help would be of Great help.Thanks in Advance

**Comment by Navya-V** [comment]
@continuum-vikrant-tyagi  can u suggest the solution for above problem? u said u will cross check, i am struggling with this issue
Thanks in advance

**Comment by Navya-V** [comment]
@nireeshT  can u look into my above issue and help!!!!

**Comment by Sjnahak** [comment]
@continuum-vikrant-tyagi   did you manage to solve the issue?
