### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by bpollard** [Hygieia/hygieia-feature-jira-collector#35]
**Affects:** 3.1.2-SNAPSHOT

---

I attempted to build the newest version of this plugin by first cloning the repo and then running mvn install. During the test I was presented with the following:

Running com.capitalone.dashboard.utils.UtilitiesTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.capitalone.dashboard.utils.UtilitiesTest

Results :

Failed tests:
  DefaultJiraClientTest.getProjectsParseException:111 expected:<[org.json.simple.JSONObject cannot be cast to org.json.simple.JSONArray]> but was:<[class org.json.simple.JSONObject cannot be cast to class org.json.simple.JSONArray (org.json.simple.JSONObject and org.json.simple.JSONArray are in unnamed module of loader 'app')]>

Tests run: 28, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.990 s
[INFO] Finished at: 2020-04-01T17:03:23-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project jira-feature-collector: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/bpollard/GIT/trhc/hygieia-feature-jira-collector/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

[com.capitalone.dashboard.collector.DefaultJiraClientTest.txt](https://github.com/Hygieia/hygieia-feature-jira-collector/files/4418196/com.capitalone.dashboard.collector.DefaultJiraClientTest.txt)

This is the last checkin as I see in my git logs.
| Author: Ragha Vema <ragha.vema@capitalone.com>
| Date:   Tue Nov 5 00:27:26 2019 -0500
|
|     Increment Version to 3.1.2-SNAPSHOT

**Comment by rvema** [comment]
Can you verify if your JAVA_HOME is set correctly? I can compile without any issues. Also we have enforced strict compilation check for every commit in this repository which means if `if mvn clean install` fails the commit cannot be merged.

**Comment by bpollard** [comment]
@rvema thank you very much. In fact I did not have JAVA_HOME set. It appears I did have it set in another shell while I was building the other plugins. Setting JAVA_HOME did fix this. I appreciate the response.
