### ISSUE TITLE
Feature Dashboard not working

### ISSUE THREAD

**Issue by karan-beyond** [Hygieia/hygieia-feature-jira-collector#54]
Hi All, 
I am working to set team dashboard with Features widget using  latest Hygieia UI (version : 1.0.0-SNAPSHOT) , API module (version : 3.3.2-SNAPSHOT) and hygieia-feature-jira-collector version (  version : 3.2.0-SN1APSHOT). 
The hygieia-feature-jira-collector  runs successfully and populate data in Teams, Scope and features table but in collector_items table. My application settings are configured to work in JiraBoard mode. 
When I am trying to add Feature widget from UI, It is making an API (/collector/item/type/searchField/{collectorType})call to verify Team & project Name. In CollectorController class, the method collectorItemsByTypeAndSearchField
 Tries to match Team & Project information from collector_items table. Which is empty in my case. 
Can you please help me to understand what is wrong. 

I have noticed that previous to [https://github.com/Hygieia/hygieia-feature-jira-collector/commit/82211d39959062bfe0f75a2e216f7faf1a91d447#diff-0f36c61a09364aeec863394ce48ae03a
](url) this change collection_items table was populated to store team data. This change is done by @Sbrenthughes 

**Affects:** \<3.2.0-SN1APSHOT>.

---

**Comment by jbadeau** [comment]
Any update here? I have the same issue.
