### ISSUE TITLE
Hygia Jeera collector access+invalid credentials

### ISSUE THREAD

**Issue by prasad12k** [hygieia/hygieia-feature-jira-collector#60]
Hi Team,

I have downloaded project from 

https://github.com/Hygieia/hygieia-feature-jira-collector

Setting up application properties and running below command in command prompt

#feature.jiraProxyUrl=http://proxy.com
#feature.jiraProxyPort=9000
feature.jiraBaseUrl=https://xxxxxxx.atlassian.net/
feature.jiraQueryEndpoint=jira/xxxxx/projects/xx/xxx/xx/xx

feature.jiraCredentials=xxxxxxxxxxx(api key)

feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

running below command in command line

java -jar [collector name].jar --spring.config.name=feature --spring.config.location=[path to application.properties file]
**Getting error invalid credentials** 

2020-11-20 06:38:00,006 [taskScheduler-1] INFO c.c.d.collector.CollectorTask - Getting Collector: Jira
2020-11-20 06:38:00,020 [taskScheduler-1] ERROR c.c.d.collector.DefaultJiraClient - Error in calling JIRA API
com.capitalone.dashboard.misc.******Exception: Invalid Jira credentials

**Comment by AdityaPramod1212** [comment]
Basic authentication with passwords is deprecated.  For more information, see: https://developer.atlassian.com/cloud/confluence/deprecation-notice-basic-auth/

This needs a new feature development to support oauth.
Has anyone integrated jira successfully after this ?
